Refactor and update code

diff --git a/share/xinputrc.common.in b/share/xinputrc.common.in
--- a/share/xinputrc.common.in
+++ b/share/xinputrc.common.in
@@ -4,7 +4,7 @@
 # vim: set sts=4 expandtab:
 #
 #############################################################
-# Common variabless used by all im-config
+# Common variabless used by im-config and its hook script
 #############################################################
 IM_CONFIG_VERSION=@@VERSION@@
 IM_CONFIG_DATA=/usr/share/im-config/data
@@ -16,37 +16,6 @@ if [ -r $IM_CONFIG_DEFAULT ]; then
     . $IM_CONFIG_DEFAULT
 fi
 #############################################################
-# Common functions used by im-config hook script (auto mode)
-#############################################################
-
-# sanity check
-# check_avail_im <config>
-check_avail_im () {
-    if [ -r $IM_CONFIG_DATA/[012345678]?_$1.dsc ]; then
-        . $IM_CONFIG_DATA/[012345678]?_$1.dsc
-        if [ "x$IM_CONFIG_KEY" = "x" ] || \
-           [ "x$IM_CONFIG_KEY" = "xnone" ]; then
-            true
-        elif [ -r $IM_CONFIG_KEY ]; then
-            true
-        else
-            false
-        fi
-    else
-        false
-    fi
-}
-
-# 
-# name_im <full_path>
-name_im () {
-    local x
-    x=${1#$IM_CONFIG_DATA/??_}
-    x=${x%.im}
-    echo -n $x
-}
-
-#############################################################
 # Common functions used by im-config hook script (any mode)
 #############################################################
 # run selected input method script
@@ -54,15 +23,64 @@ name_im () {
 run_im () {
     if [ -r $IM_CONFIG_DATA/[012345678]?_$1.im ]; then
         . $IM_CONFIG_DATA/[012345678]?_$1.im
-        export XMODIFIERS
-        export GTK_IM_MODULE
-        export QT_IM_MODULE
-        export QT4_IM_MODULE
-        export CLUTTER_IM_MODULE
-        echo "script for $1 started." >&2
+        echo -n "script for $1 started." >&2
+        echo >&2
     else
-        echo "ERROR: script for $1 not found." >&2
+        echo -n "ERROR: script for $1 not found." >&2
+        echo >&2
+    fi
+}
+#############################################################
+# Package status function used by im-config and auto mode
+#############################################################
+# package_status <packagename>
+# return TRUE if in properly installed
+package_status () {
+    PACKAGE_NAME="$1"
+    if [ "$( dpkg-query -l "$PACKAGE_NAME" 2>/dev/null | \
+        sed -n '6s/\([^ ]*\) .*$/\1/p' )" = "ii" ]; then
+        # return TRUE
+        return 0
+    else
+        return 1
+    fi
+}
+#############################################################
+# Common functions used by auto mode
+#############################################################
+# name_im <full_path>
+name_im () {
+    local x
+    x=${1#$IM_CONFIG_DATA/??_}
+    x=${x%.im}
+    x=${x%.dsc}
+    echo -n $x
+}
+# avail_auto <config>
+#   configuration availability for auto mode
+#   define package_auto for 10-79*.dsc
+avail_auto () {
+    if [ -r $IM_CONFIG_DATA/??_$1.dsc ]; then
+        . $IM_CONFIG_DATA/??_$1.dsc
+        package_auto 
+    else
+        echo "E: wrong config name: $1" >&2
+        # return FALSE
+        return 1
     fi
 }
 
+# automatic_im
+#   echo automatic IM configuration name
+automatic_im () {
+# auto mode uses first available script in 10-79
+# 79 is for "none", i.e., no IM used
+    for IM_CONFIG_SCRIPT_PATH in $IM_CONFIG_DATA/[1234567]*.im ; do
+        IM_CONFIG_SCRIPT=$(name_im $IM_CONFIG_SCRIPT_PATH)
+        if avail_auto $IM_CONFIG_SCRIPT ; then
+            echo -n "$IM_CONFIG_SCRIPT"
+            break
+        fi
+    done
+}   
 
